import EWC_CONFIG from "../client_config/ewc.js";
import {
  ROOT_NAMESPACE,
  ORG_NAME,
  ORG_NAMESPACE,
  ADMIN,
  INSTALLER,
  ELECTRICIAN,
  BUILDER,
  PV_SYSTEM,
  CONTRACTOR,
  ADMIN_ROLE_NAMESPACE,
  ORG_INSTALLER_ROLE_NAMESPACE,
  ORG_ELECTRICIAN_ROLE_NAMESPACE,
  ORG_BUILDER_ROLE_NAMESPACE,
  ORG_CONTRACTOR_ROLE_NAMESPACE,
  ORG_ROLES_NAMESPACE,
} from "../client_config/switchboard.js";
import { getInfuraIPFSConfig } from "../client_config/infura_config.js"

const WALLET_PRIVATE_KEY = process.env.WALLET_PRIVATE_KEY;

const {
  ENERGY_WEB_CHAIN_ID: CHAIN_ID,
  ENERGY_WEB_RPC_URL: RPC_URL,
  ENERGY_WEB_CACHE_SERVER_URL
} = EWC_CONFIG;

export {
  ROOT_NAMESPACE,
  ORG_NAME,
  ORG_NAMESPACE,
  ADMIN,
  INSTALLER,
  ELECTRICIAN,
  BUILDER,
  PV_SYSTEM,
  CONTRACTOR,
  ADMIN_ROLE_NAMESPACE,
  ORG_INSTALLER_ROLE_NAMESPACE,
  ORG_ELECTRICIAN_ROLE_NAMESPACE,
  ORG_BUILDER_ROLE_NAMESPACE,
  ORG_CONTRACTOR_ROLE_NAMESPACE,
  ORG_ROLES_NAMESPACE,
  getInfuraIPFSConfig,
  WALLET_PRIVATE_KEY,
  CHAIN_ID,
  RPC_URL,
  ENERGY_WEB_CACHE_SERVER_URL
}
